FROM registry.redhat.io/ubi8/ubi:latest

# ---------- dnf install ----------
# update
RUN dnf update -y

# Instsall python3.8
RUN dnf module -y install python38

RUN dnf -y install openssh-server openssh-clients net-tools sudo

# ---------- pip install ----------
# Set python3 version to 3.8
RUN alternatives --set python3 /usr/bin/python3.8

# Update pip3
RUN pip3 install --upgrade pip

# Install ansible
RUN pip3 install ansible argcomplete

# Install python module winrm
RUN pip3 install pywinrm

# Install ansible.windows
RUN ansible-galaxy collection install ansible.windows

# Install openssh-clients
RUN dnf install openssh-clients -y


# Installing the Kubernetes Collection for Ansible
## Install the OpenShift python client package
RUN pip3 install openshift

## Installing the Kubernetes Python Library
RUN pip3 install kubernetes

# ---------- ansible galaxy install ----------

## install the collection directly from Ansible Galaxy:
RUN ansible-galaxy collection install kubernetes.core

## install openshift collection
RUN ansible-galaxy collection install community.okd


# ---------- init shell ----------
RUN mkdir -p /opt/sshd
COPY ./startup.sh /opt/sshd/
RUN chmod +x /opt/sshd/startup.sh

# ---------- sshd settings ----------
# create keys for sshd
RUN ssh-keygen -A
# disable sshd config UsePAM setting
RUN sed -i 's/^UsePAM yes$/UsePAM no/' /etc/ssh/sshd_config

# ---------- user settings ----------
# change root password
RUN echo "root:Admin12345" | chpasswd

# create user student
RUN useradd -u 1000 -m test
RUN echo "test:Test12345" | chpasswd
RUN usermod -aG wheel test


ENTRYPOINT ["tail", "-f", "/dev/null"]
